In [1]:
import math
import pandas as pd

In [2]:
# Reading data from an Excel file
df = pd.read_excel("../datasets/project-1.xlsx")
df

   Escolaridade  Sexo  Idade
0      superior   fem     21
1      superior  masc     28
2   fundamental  masc     13
3         médio  masc     19
4         médio   fem     19
5      superior   fem     27
6   fundamental  masc     16
7         médio   fem     23
8   fundamental   fem     15
9      superior  masc     23
10        médio  masc     23
11     superior   fem     22
12  fundamental   fem     20
13        médio  masc     19
14     superior  masc     22
15        médio   fem     18

In [3]:
# Couting values in the 'Escolaridade' column
df['Escolaridade'].value_counts()

Escolaridade
superior       6
médio          6
fundamental    4
Name: count, dtype: int64

In [4]:
# Creating a DataFrame with the counts and frequencies of the 'Escolaridade' column
qualitative_data = pd.DataFrame(df['Escolaridade'].value_counts())
qualitative_data['frequency'] = df['Escolaridade'].value_counts(
    normalize=True).apply(lambda x: f"{x:.2%}")
qualitative_data

              count frequency
Escolaridade
superior          6    37.50%
médio             6    37.50%
fundamental       4    25.00%