In [1]:
import math
import pandas as pd

In [2]:
df = pd.read_excel('../datasets/project-1.xlsx')
df

   Escolaridade  Sexo  Idade
0      superior   fem     21
1      superior  masc     28
2   fundamental  masc     13
3         médio  masc     19
4         médio   fem     19
5      superior   fem     27
6   fundamental  masc     16
7         médio   fem     23
8   fundamental   fem     15
9      superior  masc     23
10        médio  masc     23
11     superior   fem     22
12  fundamental   fem     20
13        médio  masc     19
14     superior  masc     22
15        médio   fem     18

In [3]:
df.Escolaridade.value_counts()

Escolaridade
superior       6
médio          6
fundamental    4
Name: count, dtype: int64

In [4]:
df.Escolaridade.value_counts().sort_index()

Escolaridade
fundamental    4
médio          6
superior       6
Name: count, dtype: int64

In [5]:
qualitative_data = pd.DataFrame(df)
qualitative_data = qualitative_data.groupby(
    'Escolaridade').size().reset_index(name='count')
qualitative_data

  Escolaridade  count
0  fundamental      4
1        médio      6
2     superior      6

In [6]:
total = qualitative_data['count'].sum()
total

np.int64(16)

In [7]:
qualitative_data["Frequency %"] = round(
    qualitative_data['count'] * 100 / total, 2)
qualitative_data

  Escolaridade  count  Frequency %
0  fundamental      4         25.0
1        médio      6         37.5
2     superior      6         37.5